server:
  servlet:
    context-path: /qs
  address: localhost
  port: 8081

spring:
  main:
    banner-mode: off
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    name: raceappdb
    url: jdbc:mariadb://localhost:3306/raceappdb?sslMode=disable&allowPublicKeyRetrieval=true
    username: dev_raceapp
    password: dev_raceapp!
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.trail_race.race_application.dto.request